route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'nodejs-webhook'

receivers:
- name: 'nodejs-webhook'
  webhook_configs:
  - url: 'http://alert-receiver:3001/alert'
    send_resolved: true