global:
  scrape_interval: 3s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'nodejs'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nodejs-app:3000']